name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    verify_files:
        name: Verify Files
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Install Packages
              run: npm ci
            - name: Lint Files
              run: npm run lint
            - name: Typecheck
              run: npm run typecheck
            - name: Typecheck (React 18)
              run: |
                  npm i --no-save @types/react@18 @types/react-dom@18
                  npm run typecheck
    tests.units:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Install Packages
              run: npm ci
            - name: Unit Tests
              run: npm run test:units

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Install Packages
              run: npm ci
            - name: Build
              run: npm run build
            - name: Unit Tests
              run: npm run test:screenshots

            - name: Upload screenshots
              uses: actions/upload-artifact@v2
              with:
                  name: screenshots
                  path: tests/screenshots/tests/__image_snapshots__
