name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    verify_files:
        name: Verify Files
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Install Packages
              run: npm ci
            - name: Lint Files
              run: npm run lint
            - name: Typecheck
              run: npm run typecheck
            - name: Typecheck (React 18)
              run: |
                  npm i --no-save @types/react@18 @types/react-dom@18
                  npm run typecheck

    tests_units:
        name: Unit testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
                  cache: 'npm'
            - name: Install Packages
              run: npm ci
            - name: Unit Tests
              run: npm run test:units

    test_screenshots:
        name: Screenshot testing
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'
                  cache: 'npm'

            - name: Install Packages
              run: npm ci
            - name: Build
              run: npm run build
            - name: Run tests
              run: npm run test:screenshots -- --updateSnapshot

            - name: Commit
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "robot@gravity-ui.com"
                  git add .
                  git commit -m "Update screenshots test"
                  git push origin test/screenshots
